import os
import uuid
import json
import re
import math
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit log helpers ──────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_entry(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


# ── Signal 1: Groq LLM classifier ─────────────────────────────────

def groq_signal(text):
    """
    Asks the LLM to score how likely the text is AI-generated.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI.

Analyze the following text and respond with ONLY a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

0.0 means certainly human-written. 1.0 means certainly AI-generated.

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    # Strip markdown code fences if present
    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    result = json.loads(raw)
    score = float(result["ai_probability"])
    return max(0.0, min(1.0, score))  # clamp to [0, 1]


# ── Signal 2: Stylometric heuristics ──────────────────────────────

def stylo_signal(text):
    """
    Measures structural/statistical properties of the text.
    Returns a float from 0.0 (human) to 1.0 (AI).
    AI text tends to be more uniform; human text more variable.
    """
    # Split into sentences
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5  # not enough data, return uncertain

    # --- Metric 1: Sentence length variance ---
    # AI text tends to have similar sentence lengths
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)

    # Low std_dev = uniform = more AI-like
    # Normalize: std_dev of 8+ is very human, 2 or less is very AI
    length_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # --- Metric 2: Type-token ratio (vocabulary diversity) ---
    words = re.findall(r'\b[a-z]+\b', text.lower())
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)

    # High TTR = diverse vocabulary = more human
    # Normalize: TTR > 0.8 is very human, < 0.5 is more AI-like
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.3)))

    # --- Metric 3: Punctuation density ---
    # Human writing uses more varied punctuation
    punct_chars = set('",;:—–()[]{}\'\"')
    punct_count = sum(1 for c in text if c in punct_chars)
    punct_density = punct_count / max(len(text), 1)

    # Low punctuation density = more AI-like
    # Normalize: density > 0.05 is human-like, < 0.01 is AI-like
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.05)))

    # Combine three metrics equally
    stylo_score = (length_score + ttr_score + punct_score) / 3.0
    return round(stylo_score, 4)


# ── Confidence scorer ──────────────────────────────────────────────

def compute_confidence(llm_score, stylo_score):
    """
    Combines both signals into a single confidence score.
    LLM gets 60% weight, stylometrics 40%.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    return round((llm_score * 0.6) + (stylo_score * 0.4), 4)


def get_attribution(confidence):
    if confidence >= 0.65:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Routes ─────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"]

    if len(text) < 20:
        return jsonify({"error": "Text too short for analysis"}), 400

    content_id = str(uuid.uuid4())

    # Both signals
    llm_score = groq_signal(text)
    stylo_score = stylo_signal(text)

    # Combined confidence
    confidence = compute_confidence(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = f"[Placeholder label — confidence {confidence}]"

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    append_entry(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})


if __name__ == "__main__":
    app.run(debug=True)