import os
import uuid
import json
import re
import math
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit log helpers ──────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_entry(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


def find_entry(content_id):
    entries = read_log()
    for i, entry in enumerate(entries):
        if entry["content_id"] == content_id:
            return i, entries
    return None, entries


# ── Signal 1: Groq LLM classifier ─────────────────────────────────

def groq_signal(text):
    """
    Asks the LLM to score how likely the text is AI-generated.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI.

Analyze the following text and respond with ONLY a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

0.0 means certainly human-written. 1.0 means certainly AI-generated.

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    result = json.loads(raw)
    score = float(result["ai_probability"])
    return max(0.0, min(1.0, score))


# ── Signal 2: Stylometric heuristics ──────────────────────────────

def stylo_signal(text):
    """
    Measures structural/statistical properties of the text.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5

    # Metric 1: Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    length_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # Metric 2: Type-token ratio
    words = re.findall(r'\b[a-z]+\b', text.lower())
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.3)))

    # Metric 3: Punctuation density
    punct_chars = set('",;:—–()[]{}\'\"')
    punct_count = sum(1 for c in text if c in punct_chars)
    punct_density = punct_count / max(len(text), 1)
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.05)))

    stylo_score = (length_score + ttr_score + punct_score) / 3.0
    return round(stylo_score, 4)


# ── Signal 3: Filler phrase detection ─────────────────────────────

def filler_signal(text):
    """
    Detects AI-characteristic filler and transitional phrases.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    filler_phrases = [
        "it is important to note",
        "it is worth mentioning",
        "it is worth noting",
        "furthermore",
        "in conclusion",
        "in today's world",
        "in the modern world",
        "it is essential to",
        "it is crucial to",
        "one must consider",
        "it goes without saying",
        "needless to say",
        "as previously mentioned",
        "in summary",
        "to summarize",
        "on the other hand",
        "it should be noted",
        "in this day and age",
        "at the end of the day",
        "when it comes to",
        "it is imperative",
        "a wide range of",
        "a variety of",
        "in terms of",
        "it is undeniable",
        "there is no doubt",
        "plays a crucial role",
        "plays an important role",
        "delve into",
        "dive into",
        "in the realm of",
        "it is fascinating",
        "it is interesting to note",
    ]

    text_lower = text.lower()
    word_count = max(len(text.split()), 1)

    # Count how many filler phrases appear
    hits = sum(1 for phrase in filler_phrases if phrase in text_lower)

    # Normalize by word count — more hits per word = more AI-like
    # A single hit in a short text is significant; scale up to ~3 hits per
    # 100 words as the maximum before clamping to 1.0
    density = hits / (word_count / 100)
    score = max(0.0, min(1.0, density / 3.0))
    return round(score, 4)


# ── Confidence scorer ──────────────────────────────────────────────

def compute_confidence(llm_score, stylo_score, filler_score):
    """
    Combines all three signals into a single confidence score.
    LLM: 50%, Stylometrics: 30%, Filler phrases: 20%
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    return round(
        (llm_score * 0.5) + (stylo_score * 0.3) + (filler_score * 0.2),
        4
    )


def get_attribution(confidence):
    if confidence >= 0.65:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Transparency label generator ───────────────────────────────────

def generate_label(attribution, confidence):
    pct = round(confidence * 100)

    if attribution == "likely_ai" and confidence >= 0.75:
        return (
            f"AI-Generated Content — "
            f"Our analysis strongly suggests this piece was AI-generated "
            f"(confidence: {pct}%). "
            f"If you are the creator and believe this is incorrect, "
            f"you can submit an appeal."
        )
    elif attribution == "likely_ai":
        return (
            f"Likely AI-Generated — "
            f"Our analysis suggests this piece may be AI-generated, "
            f"though we are not certain (confidence: {pct}%). "
            f"If you are the creator and believe this is incorrect, "
            f"you can submit an appeal."
        )
    elif attribution == "likely_human" and confidence <= 0.25:
        return (
            f"Human-Written Content — "
            f"Our analysis strongly suggests this piece was written "
            f"by a human (confidence: {pct}%)."
        )
    elif attribution == "likely_human":
        return (
            f"Likely Human-Written — "
            f"Our analysis suggests this piece was probably written "
            f"by a human (confidence: {pct}%)."
        )
    else:
        return (
            f"Attribution Uncertain — "
            f"We were unable to confidently determine whether this piece "
            f"was written by a human or generated by AI (confidence: {pct}%). "
            f"The author has not been flagged and this content remains fully visible. "
            f"Creators may submit an appeal to provide additional context."
        )


# ── Routes ─────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"]

    if len(text) < 20:
        return jsonify({"error": "Text too short for analysis"}), 400

    content_id = str(uuid.uuid4())

    # All three signals
    llm_score = groq_signal(text)
    stylo_score = stylo_signal(text)
    filler_score = filler_signal(text)

    # Combined confidence
    confidence = compute_confidence(llm_score, stylo_score, filler_score)
    attribution = get_attribution(confidence)
    label = generate_label(attribution, confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "filler_score": filler_score,
        "status": "classified",
        "appeal_reasoning": None,
        "provenance_certificate": None,
    }
    append_entry(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
        "signals": {
            "llm_score": llm_score,
            "stylo_score": stylo_score,
            "filler_score": filler_score,
        }
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Request must include 'content_id' and 'creator_reasoning'"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"].strip()

    if not reasoning:
        return jsonify({"error": "creator_reasoning cannot be empty"}), 400

    idx, entries = find_entry(content_id)

    if idx is None:
        return jsonify({"error": "content_id not found"}), 404

    entries[idx]["status"] = "under_review"
    entries[idx]["appeal_reasoning"] = reasoning
    entries[idx]["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
    write_log(entries)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and logged. A human reviewer will assess your submission.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})


@app.route("/verify", methods=["POST"])
def verify():
    data = request.get_json()

    if not data or "content_id" not in data or "verification_statement" not in data:
        return jsonify({"error": "Request must include 'content_id' and 'verification_statement'"}), 400

    content_id = data["content_id"]
    statement = data["verification_statement"].strip()

    if not statement:
        return jsonify({"error": "verification_statement cannot be empty"}), 400

    idx, entries = find_entry(content_id)

    if idx is None:
        return jsonify({"error": "content_id not found"}), 404

    # Only allow verification for human or uncertain content
    attribution = entries[idx]["attribution"]
    if attribution == "likely_ai":
        return jsonify({
            "error": "Provenance certificate not available for content classified as likely_ai. "
                     "Please submit an appeal first if you believe this is incorrect."
        }), 403

    # Issue the certificate
    certificate = {
        "certified": True,
        "issued_at": datetime.now(timezone.utc).isoformat(),
        "verification_statement": statement,
        "badge": "✓ Verified Human-Written",
    }

    entries[idx]["provenance_certificate"] = certificate
    write_log(entries)

    return jsonify({
        "content_id": content_id,
        "badge": "✓ Verified Human-Written",
        "issued_at": certificate["issued_at"],
        "message": "Your provenance certificate has been issued and attached to this content.",
        "certificate": certificate,
    })

@app.route("/dashboard", methods=["GET"])
def dashboard():
    entries = read_log()

    total = len(entries)
    if total == 0:
        counts = {"likely_ai": 0, "uncertain": 0, "likely_human": 0}
        appeal_rate = 0.0
        avg_confidence = 0.0
        cert_rate = 0.0
    else:
        # Attribution breakdown
        counts = {"likely_ai": 0, "uncertain": 0, "likely_human": 0}
        for e in entries:
            counts[e["attribution"]] = counts.get(e["attribution"], 0) + 1

        # Appeal rate
        appeals = sum(1 for e in entries if e.get("appeal_reasoning"))
        appeal_rate = round(appeals / total * 100, 1)

        # Average confidence
        avg_confidence = round(
            sum(e["confidence"] for e in entries) / total, 4
        )

        # Certificate rate (bonus metric)
        certified = sum(
            1 for e in entries if e.get("provenance_certificate")
        )
        cert_rate = round(certified / total * 100, 1)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Provenance Guard — Analytics Dashboard</title>
    <style>
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}

        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background: #f4f5f7;
            color: #1a1a2e;
            padding: 40px 20px;
        }}

        h1 {{
            font-size: 1.6rem;
            font-weight: 700;
            margin-bottom: 6px;
        }}

        .subtitle {{
            color: #666;
            font-size: 0.9rem;
            margin-bottom: 36px;
        }}

        .grid {{
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 20px;
            margin-bottom: 36px;
        }}

        .card {{
            background: white;
            border-radius: 12px;
            padding: 24px;
            box-shadow: 0 1px 4px rgba(0,0,0,0.08);
        }}

        .card .value {{
            font-size: 2.2rem;
            font-weight: 700;
            margin-bottom: 4px;
        }}

        .card .label {{
            font-size: 0.82rem;
            color: #888;
            text-transform: uppercase;
            letter-spacing: 0.05em;
        }}

        .card.ai .value   {{ color: #e05252; }}
        .card.human .value {{ color: #3aaa6e; }}
        .card.uncertain .value {{ color: #e09a2f; }}
        .card.neutral .value {{ color: #4a6fa5; }}

        .section-title {{
            font-size: 1rem;
            font-weight: 600;
            margin-bottom: 16px;
        }}

        .bar-row {{
            display: flex;
            align-items: center;
            gap: 12px;
            margin-bottom: 12px;
        }}

        .bar-label {{
            width: 120px;
            font-size: 0.85rem;
            color: #444;
        }}

        .bar-track {{
            flex: 1;
            background: #eee;
            border-radius: 99px;
            height: 10px;
            overflow: hidden;
        }}

        .bar-fill {{
            height: 100%;
            border-radius: 99px;
        }}

        .bar-fill.ai       {{ background: #e05252; }}
        .bar-fill.human    {{ background: #3aaa6e; }}
        .bar-fill.uncertain {{ background: #e09a2f; }}

        .bar-pct {{
            font-size: 0.82rem;
            color: #888;
            width: 40px;
            text-align: right;
        }}

        .footer {{
            margin-top: 40px;
            font-size: 0.78rem;
            color: #aaa;
            text-align: center;
        }}
    </style>
</head>
<body>
    <h1>Provenance Guard</h1>
    <p class="subtitle">Analytics Dashboard — all-time statistics</p>

    <div class="grid">
        <div class="card neutral">
            <div class="value">{total}</div>
            <div class="label">Total Submissions</div>
        </div>
        <div class="card ai">
            <div class="value">{counts['likely_ai']}</div>
            <div class="label">Likely AI</div>
        </div>
        <div class="card human">
            <div class="value">{counts['likely_human']}</div>
            <div class="label">Likely Human</div>
        </div>
        <div class="card uncertain">
            <div class="value">{counts['uncertain']}</div>
            <div class="label">Uncertain</div>
        </div>
        <div class="card neutral">
            <div class="value">{appeal_rate}%</div>
            <div class="label">Appeal Rate</div>
        </div>
        <div class="card neutral">
            <div class="value">{avg_confidence}</div>
            <div class="label">Avg Confidence Score</div>
        </div>
        <div class="card human">
            <div class="value">{cert_rate}%</div>
            <div class="label">Provenance Certified</div>
        </div>
    </div>

    <div class="card">
        <p class="section-title">Attribution Breakdown</p>

        <div class="bar-row">
            <div class="bar-label">Likely AI</div>
            <div class="bar-track">
                <div class="bar-fill ai"
                     style="width: {round(counts['likely_ai'] / max(total,1) * 100, 1)}%">
                </div>
            </div>
            <div class="bar-pct">
                {round(counts['likely_ai'] / max(total,1) * 100, 1)}%
            </div>
        </div>

        <div class="bar-row">
            <div class="bar-label">Likely Human</div>
            <div class="bar-track">
                <div class="bar-fill human"
                     style="width: {round(counts['likely_human'] / max(total,1) * 100, 1)}%">
                </div>
            </div>
            <div class="bar-pct">
                {round(counts['likely_human'] / max(total,1) * 100, 1)}%
            </div>
        </div>

        <div class="bar-row">
            <div class="bar-label">Uncertain</div>
            <div class="bar-track">
                <div class="bar-fill uncertain"
                     style="width: {round(counts['uncertain'] / max(total,1) * 100, 1)}%">
                </div>
            </div>
            <div class="bar-pct">
                {round(counts['uncertain'] / max(total,1) * 100, 1)}%
            </div>
        </div>
    </div>

    <p class="footer">
        Provenance Guard &mdash; data sourced from audit_log.json
    </p>
</body>
</html>"""

    return html


if __name__ == "__main__":
    app.run(debug=True)