import os
import uuid
import json
import re
import math
from datetime import datetime, timezone

from dotenv import load_dotenv
from flask import Flask, jsonify, request
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from groq import Groq

load_dotenv()

app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))

LOG_FILE = "audit_log.json"


# ── Audit log helpers ──────────────────────────────────────────────

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)


def write_log(entries):
    with open(LOG_FILE, "w") as f:
        json.dump(entries, f, indent=2)


def append_entry(entry):
    entries = read_log()
    entries.append(entry)
    write_log(entries)


def find_entry(content_id):
    entries = read_log()
    for i, entry in enumerate(entries):
        if entry["content_id"] == content_id:
            return i, entries
    return None, entries


# ── Signal 1: Groq LLM classifier ─────────────────────────────────

def groq_signal(text):
    """
    Asks the LLM to score how likely the text is AI-generated.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI.

Analyze the following text and respond with ONLY a JSON object in this exact format:
{{"ai_probability": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

0.0 means certainly human-written. 1.0 means certainly AI-generated.

Text to analyze:
\"\"\"{text}\"\"\"
"""
    response = groq_client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    if raw.startswith("```"):
        raw = raw.split("```")[1]
        if raw.startswith("json"):
            raw = raw[4:]
    raw = raw.strip()

    result = json.loads(raw)
    score = float(result["ai_probability"])
    return max(0.0, min(1.0, score))


# ── Signal 2: Stylometric heuristics ──────────────────────────────

def stylo_signal(text):
    """
    Measures structural/statistical properties of the text.
    Returns a float from 0.0 (human) to 1.0 (AI).
    """
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]

    if len(sentences) < 2:
        return 0.5

    # Metric 1: Sentence length variance
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    std_dev = math.sqrt(variance)
    length_score = max(0.0, min(1.0, 1.0 - (std_dev / 8.0)))

    # Metric 2: Type-token ratio
    words = re.findall(r'\b[a-z]+\b', text.lower())
    if len(words) == 0:
        return 0.5
    ttr = len(set(words)) / len(words)
    ttr_score = max(0.0, min(1.0, 1.0 - ((ttr - 0.5) / 0.3)))

    # Metric 3: Punctuation density
    punct_chars = set('",;:—–()[]{}\'\"')
    punct_count = sum(1 for c in text if c in punct_chars)
    punct_density = punct_count / max(len(text), 1)
    punct_score = max(0.0, min(1.0, 1.0 - (punct_density / 0.05)))

    stylo_score = (length_score + ttr_score + punct_score) / 3.0
    return round(stylo_score, 4)


# ── Confidence scorer ──────────────────────────────────────────────

def compute_confidence(llm_score, stylo_score):
    return round((llm_score * 0.6) + (stylo_score * 0.4), 4)


def get_attribution(confidence):
    if confidence >= 0.65:
        return "likely_ai"
    elif confidence <= 0.35:
        return "likely_human"
    else:
        return "uncertain"


# ── Transparency label generator ───────────────────────────────────

def generate_label(attribution, confidence):
    pct = round(confidence * 100)

    if attribution == "likely_ai" and confidence >= 0.75:
        return (
            f"AI-Generated Content — "
            f"Our analysis strongly suggests this piece was AI-generated "
            f"(confidence: {pct}%). "
            f"If you are the creator and believe this is incorrect, "
            f"you can submit an appeal."
        )
    elif attribution == "likely_ai":
        return (
            f"Likely AI-Generated — "
            f"Our analysis suggests this piece may be AI-generated, "
            f"though we are not certain (confidence: {pct}%). "
            f"If you are the creator and believe this is incorrect, "
            f"you can submit an appeal."
        )
    elif attribution == "likely_human" and confidence <= 0.25:
        return (
            f"Human-Written Content — "
            f"Our analysis strongly suggests this piece was written "
            f"by a human (confidence: {pct}%)."
        )
    elif attribution == "likely_human":
        return (
            f"Likely Human-Written — "
            f"Our analysis suggests this piece was probably written "
            f"by a human (confidence: {pct}%)."
        )
    else:
        return (
            f"Attribution Uncertain — "
            f"We were unable to confidently determine whether this piece "
            f"was written by a human or generated by AI (confidence: {pct}%). "
            f"The author has not been flagged and this content remains fully visible. "
            f"Creators may submit an appeal to provide additional context."
        )


# ── Routes ─────────────────────────────────────────────────────────

@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()

    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Request must include 'text' and 'creator_id'"}), 400

    text = data["text"].strip()
    creator_id = data["creator_id"]

    if len(text) < 20:
        return jsonify({"error": "Text too short for analysis"}), 400

    content_id = str(uuid.uuid4())

    llm_score = groq_signal(text)
    stylo_score = stylo_signal(text)
    confidence = compute_confidence(llm_score, stylo_score)
    attribution = get_attribution(confidence)
    label = generate_label(attribution, confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.now(timezone.utc).isoformat(),
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified",
        "appeal_reasoning": None,
    }
    append_entry(entry)

    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label,
    })


@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()

    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Request must include 'content_id' and 'creator_reasoning'"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"].strip()

    if not reasoning:
        return jsonify({"error": "creator_reasoning cannot be empty"}), 400

    idx, entries = find_entry(content_id)

    if idx is None:
        return jsonify({"error": "content_id not found"}), 404

    entries[idx]["status"] = "under_review"
    entries[idx]["appeal_reasoning"] = reasoning
    entries[idx]["appeal_timestamp"] = datetime.now(timezone.utc).isoformat()
    write_log(entries)

    return jsonify({
        "content_id": content_id,
        "status": "under_review",
        "message": "Your appeal has been received and logged. A human reviewer will assess your submission.",
    })


@app.route("/log", methods=["GET"])
def get_log():
    entries = read_log()
    return jsonify({"entries": entries[-20:]})


if __name__ == "__main__":
    app.run(debug=True)